version: "3"

services:
  dxc-server:
    image: ashlesh/dxc
    volumes:
      - ./files:/go/files
    ports:
      - "7778:8080"
    env_file:
      - .env
    restart: on-failure
  dxc-ui:
    image: ashlesh/dxc-ui
    ports:
      - "7777:80"
    env_file:
      - .env
